### ISSUE TITLE
Render image/video in command line

### ISSUE THREAD

**Issue by kiootic** [kiootic/pad-resources#3]

**Comment by Mapaler** [comment]
I think we could consider outputing the png sequence so that it can be converted to support for transparent **APNG** or **WebP**.
[webp animate test.zip](https://github.com/kiootic/pad-resources/files/5615697/webp.animate.test.zip)

\<img2webp\> doc: https://developers.google.com/speed/webp/docs/img2webp 
\<libwebp\> down: https://storage.googleapis.com/downloads.webmproject.org/releases/webp/index.html

**Comment by kiootic** [comment]
Fixed by 075e6b3d7edb71974814e718d6429c345b6f4072.

Sample usage: `node ./render.js ../data/HT/out/mons_4355.json --no-bg --out-dir frames`
